---
  Octavia.create_and_balance_http_vms:
    -
      args:
        flavor:
            name: "m1.tiny"
        image:
            name: "^cirros.*-disk$"
        floating_net:
            name: "ext-net"
        username: "ubuntu"
      runner:
        type: "constant"
        times: 1
        concurrency: 1
      context:
        users:
          tenants: 1
        roles:
        - load-balancer_member
        network: {}
      sla:
        failure_rate:
          max: 0
